# This is a basic workflow to help you get started with Actions

name: Docs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: Generate Documentation
        run: |
          make docs
          cp -r docs/build/html/* ./docs
          touch docs/.nojekyll
      - name: Commit Documentation
        uses: EndBug/add-and-commit@v7
        with:
          message: 'autogen(docs): update documentation'
          signoff: true
          author_name: ci-build
          author_email: 'no-reply@github.com'
          branch: 'docs'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
